version: '3.8'

services:
  unillm:
    image: unillm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3000"  # Exponha a porta desejada
    volumes:
      - .:/app       # Monte o diretório atual no container
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1 
    command: flask run --host=0.0.0.0 --port=3000  # Comando para rodar a aplicação; ajuste se necessário
    restart: unless-stopped  # Política de reinício
