version: '3.8'

services:
  unillm:
    image: unillm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Porta padrão da aplicação
    volumes:
      - .:/app       # Monte o diretório atual no container
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1 
      # Força o uso de host.docker.internal para acessar o Ollama na máquina host
      - OLLAMA_HOST=host.docker.internal
    command: python app.py  # Usando o app.py diretamente para usar nossas configurações
    restart: unless-stopped  # Política de reinício
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Necessário para acessar a máquina host em alguns sistemas
