model_list:
  - model_name: sourceful/riverflow-v2-pro
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-pro
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-pro
      pool: free-models-image
  - model_name: sourceful/riverflow-v2-fast
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-fast
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-fast
      pool: free-models-image
  - model_name: black-forest-labs/flux.2-klein-4b
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-klein-4b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-klein-4b
      pool: free-models-image
  - model_name: bytedance-seed/seedream-4.5
    litellm_params:
      model: openrouter/bytedance-seed/seedream-4.5
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: bytedance-seed/seedream-4.5
      pool: free-models-image
  - model_name: black-forest-labs/flux.2-max
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-max
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-max
      pool: free-models-image
  - model_name: sourceful/riverflow-v2-max-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-max-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-max-preview
      pool: free-models-image
  - model_name: sourceful/riverflow-v2-standard-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-standard-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-standard-preview
      pool: free-models-image
  - model_name: sourceful/riverflow-v2-fast-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-fast-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-fast-preview
      pool: free-models-image
  - model_name: black-forest-labs/flux.2-flex
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-flex
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-flex
      pool: free-models-image
  - model_name: black-forest-labs/flux.2-pro
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-pro
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-pro
      pool: free-models-image
  - model_name: nvidia/llama-nemotron-embed-vl-1b-v2
    litellm_params:
      model: openrouter/nvidia/llama-nemotron-embed-vl-1b-v2
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/llama-nemotron-embed-vl-1b-v2
      pool: free-models-embedding
  - model_name: hunter-alpha
    litellm_params:
      model: openrouter/hunter-alpha
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: hunter-alpha
      pool: free-models-text
  - model_name: healer-alpha
    litellm_params:
      model: openrouter/healer-alpha
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: healer-alpha
      pool: free-models-text
  - model_name: nvidia/nemotron-3-super-120b-a12b
    litellm_params:
      model: openrouter/nvidia/nemotron-3-super-120b-a12b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-3-super-120b-a12b
      pool: free-models-text
  - model_name: stepfun/step-3.5-flash
    litellm_params:
      model: openrouter/stepfun/step-3.5-flash
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: stepfun/step-3.5-flash
      pool: free-models-text
  - model_name: arcee-ai/trinity-large-preview
    litellm_params:
      model: openrouter/arcee-ai/trinity-large-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: arcee-ai/trinity-large-preview
      pool: free-models-text
  - model_name: liquid/lfm-2.5-1.2b-thinking
    litellm_params:
      model: openrouter/liquid/lfm-2.5-1.2b-thinking
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: liquid/lfm-2.5-1.2b-thinking
      pool: free-models-text
  - model_name: liquid/lfm-2.5-1.2b-instruct
    litellm_params:
      model: openrouter/liquid/lfm-2.5-1.2b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: liquid/lfm-2.5-1.2b-instruct
      pool: free-models-text
  - model_name: nvidia/nemotron-3-nano-30b-a3b
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-3-nano-30b-a3b
      pool: free-models-text
  - model_name: arcee-ai/trinity-mini
    litellm_params:
      model: openrouter/arcee-ai/trinity-mini
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: arcee-ai/trinity-mini
      pool: free-models-text
  - model_name: nvidia/nemotron-nano-12b-v2-vl
    litellm_params:
      model: openrouter/nvidia/nemotron-nano-12b-v2-vl
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-nano-12b-v2-vl
      pool: free-models-text
  - model_name: qwen/qwen3-next-80b-a3b-instruct
    litellm_params:
      model: openrouter/qwen/qwen3-next-80b-a3b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-next-80b-a3b-instruct
      pool: free-models-text
  - model_name: nvidia/nemotron-nano-9b-v2
    litellm_params:
      model: openrouter/nvidia/nemotron-nano-9b-v2
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-nano-9b-v2
      pool: free-models-text
  - model_name: openai/gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: openai/gpt-oss-120b
      pool: free-models-text
  - model_name: openai/gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: openai/gpt-oss-20b
      pool: free-models-text
  - model_name: z-ai/glm-4.5-air
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: z-ai/glm-4.5-air
      pool: free-models-text
  - model_name: qwen/qwen3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-coder
      pool: free-models-text
  - model_name: cognitivecomputations/dolphin-mistral-24b-venice-edition
    litellm_params:
      model: openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: cognitivecomputations/dolphin-mistral-24b-venice-edition
      pool: free-models-text
  - model_name: google/gemma-3n-e2b-it
    litellm_params:
      model: openrouter/google/gemma-3n-e2b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3n-e2b-it
      pool: free-models-text
  - model_name: google/gemma-3n-e4b-it
    litellm_params:
      model: openrouter/google/gemma-3n-e4b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3n-e4b-it
      pool: free-models-text
  - model_name: qwen/qwen3-4b
    litellm_params:
      model: openrouter/qwen/qwen3-4b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-4b
      pool: free-models-text
  - model_name: mistralai/mistral-small-3.1-24b-instruct
    litellm_params:
      model: openrouter/mistralai/mistral-small-3.1-24b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: mistralai/mistral-small-3.1-24b-instruct
      pool: free-models-text
  - model_name: google/gemma-3-4b-it
    litellm_params:
      model: openrouter/google/gemma-3-4b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-4b-it
      pool: free-models-text
  - model_name: google/gemma-3-12b-it
    litellm_params:
      model: openrouter/google/gemma-3-12b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-12b-it
      pool: free-models-text
  - model_name: google/gemma-3-27b-it
    litellm_params:
      model: openrouter/google/gemma-3-27b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-27b-it
      pool: free-models-text
  - model_name: meta-llama/llama-3.3-70b-instruct
    litellm_params:
      model: openrouter/meta-llama/llama-3.3-70b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: meta-llama/llama-3.3-70b-instruct
      pool: free-models-text
  - model_name: meta-llama/llama-3.2-3b-instruct
    litellm_params:
      model: openrouter/meta-llama/llama-3.2-3b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: meta-llama/llama-3.2-3b-instruct
      pool: free-models-text
  - model_name: nousresearch/hermes-3-llama-3.1-405b
    litellm_params:
      model: openrouter/nousresearch/hermes-3-llama-3.1-405b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nousresearch/hermes-3-llama-3.1-405b
      pool: free-models-text
  - model_name: openrouter/sourceful/riverflow-v2-pro
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-pro
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-pro
      pool: free-models-image
  - model_name: openrouter/sourceful/riverflow-v2-fast
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-fast
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-fast
      pool: free-models-image
  - model_name: openrouter/black-forest-labs/flux.2-klein-4b
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-klein-4b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-klein-4b
      pool: free-models-image
  - model_name: openrouter/bytedance-seed/seedream-4.5
    litellm_params:
      model: openrouter/bytedance-seed/seedream-4.5
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: bytedance-seed/seedream-4.5
      pool: free-models-image
  - model_name: openrouter/black-forest-labs/flux.2-max
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-max
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-max
      pool: free-models-image
  - model_name: openrouter/sourceful/riverflow-v2-max-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-max-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-max-preview
      pool: free-models-image
  - model_name: openrouter/sourceful/riverflow-v2-standard-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-standard-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-standard-preview
      pool: free-models-image
  - model_name: openrouter/sourceful/riverflow-v2-fast-preview
    litellm_params:
      model: openrouter/sourceful/riverflow-v2-fast-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: sourceful/riverflow-v2-fast-preview
      pool: free-models-image
  - model_name: openrouter/black-forest-labs/flux.2-flex
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-flex
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-flex
      pool: free-models-image
  - model_name: openrouter/black-forest-labs/flux.2-pro
    litellm_params:
      model: openrouter/black-forest-labs/flux.2-pro
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: black-forest-labs/flux.2-pro
      pool: free-models-image
  - model_name: openrouter/nvidia/llama-nemotron-embed-vl-1b-v2
    litellm_params:
      model: openrouter/nvidia/llama-nemotron-embed-vl-1b-v2
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/llama-nemotron-embed-vl-1b-v2
      pool: free-models-embedding
  - model_name: openrouter/hunter-alpha
    litellm_params:
      model: openrouter/hunter-alpha
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: hunter-alpha
      pool: free-models-text
  - model_name: openrouter/healer-alpha
    litellm_params:
      model: openrouter/healer-alpha
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: healer-alpha
      pool: free-models-text
  - model_name: openrouter/nvidia/nemotron-3-super-120b-a12b
    litellm_params:
      model: openrouter/nvidia/nemotron-3-super-120b-a12b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-3-super-120b-a12b
      pool: free-models-text
  - model_name: openrouter/stepfun/step-3.5-flash
    litellm_params:
      model: openrouter/stepfun/step-3.5-flash
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: stepfun/step-3.5-flash
      pool: free-models-text
  - model_name: openrouter/arcee-ai/trinity-large-preview
    litellm_params:
      model: openrouter/arcee-ai/trinity-large-preview
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: arcee-ai/trinity-large-preview
      pool: free-models-text
  - model_name: openrouter/liquid/lfm-2.5-1.2b-thinking
    litellm_params:
      model: openrouter/liquid/lfm-2.5-1.2b-thinking
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: liquid/lfm-2.5-1.2b-thinking
      pool: free-models-text
  - model_name: openrouter/liquid/lfm-2.5-1.2b-instruct
    litellm_params:
      model: openrouter/liquid/lfm-2.5-1.2b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: liquid/lfm-2.5-1.2b-instruct
      pool: free-models-text
  - model_name: openrouter/nvidia/nemotron-3-nano-30b-a3b
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-3-nano-30b-a3b
      pool: free-models-text
  - model_name: openrouter/arcee-ai/trinity-mini
    litellm_params:
      model: openrouter/arcee-ai/trinity-mini
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: arcee-ai/trinity-mini
      pool: free-models-text
  - model_name: openrouter/nvidia/nemotron-nano-12b-v2-vl
    litellm_params:
      model: openrouter/nvidia/nemotron-nano-12b-v2-vl
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-nano-12b-v2-vl
      pool: free-models-text
  - model_name: openrouter/qwen/qwen3-next-80b-a3b-instruct
    litellm_params:
      model: openrouter/qwen/qwen3-next-80b-a3b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-next-80b-a3b-instruct
      pool: free-models-text
  - model_name: openrouter/nvidia/nemotron-nano-9b-v2
    litellm_params:
      model: openrouter/nvidia/nemotron-nano-9b-v2
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-nano-9b-v2
      pool: free-models-text
  - model_name: openrouter/openai/gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: openai/gpt-oss-120b
      pool: free-models-text
  - model_name: openrouter/openai/gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: openai/gpt-oss-20b
      pool: free-models-text
  - model_name: openrouter/z-ai/glm-4.5-air
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: z-ai/glm-4.5-air
      pool: free-models-text
  - model_name: openrouter/qwen/qwen3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-coder
      pool: free-models-text
  - model_name: openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition
    litellm_params:
      model: openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: cognitivecomputations/dolphin-mistral-24b-venice-edition
      pool: free-models-text
  - model_name: openrouter/google/gemma-3n-e2b-it
    litellm_params:
      model: openrouter/google/gemma-3n-e2b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3n-e2b-it
      pool: free-models-text
  - model_name: openrouter/google/gemma-3n-e4b-it
    litellm_params:
      model: openrouter/google/gemma-3n-e4b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3n-e4b-it
      pool: free-models-text
  - model_name: openrouter/qwen/qwen3-4b
    litellm_params:
      model: openrouter/qwen/qwen3-4b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: qwen/qwen3-4b
      pool: free-models-text
  - model_name: openrouter/mistralai/mistral-small-3.1-24b-instruct
    litellm_params:
      model: openrouter/mistralai/mistral-small-3.1-24b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: mistralai/mistral-small-3.1-24b-instruct
      pool: free-models-text
  - model_name: openrouter/google/gemma-3-4b-it
    litellm_params:
      model: openrouter/google/gemma-3-4b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-4b-it
      pool: free-models-text
  - model_name: openrouter/google/gemma-3-12b-it
    litellm_params:
      model: openrouter/google/gemma-3-12b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-12b-it
      pool: free-models-text
  - model_name: openrouter/google/gemma-3-27b-it
    litellm_params:
      model: openrouter/google/gemma-3-27b-it
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: google/gemma-3-27b-it
      pool: free-models-text
  - model_name: openrouter/meta-llama/llama-3.3-70b-instruct
    litellm_params:
      model: openrouter/meta-llama/llama-3.3-70b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: meta-llama/llama-3.3-70b-instruct
      pool: free-models-text
  - model_name: openrouter/meta-llama/llama-3.2-3b-instruct
    litellm_params:
      model: openrouter/meta-llama/llama-3.2-3b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: meta-llama/llama-3.2-3b-instruct
      pool: free-models-text
  - model_name: openrouter/nousresearch/hermes-3-llama-3.1-405b
    litellm_params:
      model: openrouter/nousresearch/hermes-3-llama-3.1-405b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nousresearch/hermes-3-llama-3.1-405b
      pool: free-models-text
litellm_settings:
  set_model_in_response: true
