model_list:
  - model_name: openrouter/hunter-alpha
    litellm_params:
      model: openrouter/openrouter/hunter-alpha
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: openrouter/hunter-alpha
      pool: free-models-text
  - model_name: nvidia/nemotron-3-super-120b-a12b:free
    litellm_params:
      model: openrouter/nvidia/nemotron-3-super-120b-a12b:free
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      id: nvidia/nemotron-3-super-120b-a12b:free
      pool: free-models-text
router_settings:
  num_retries: 0
  fallbacks:
    - openrouter/hunter-alpha:
        - nvidia/nemotron-3-super-120b-a12b:free
litellm_settings:
  set_model_in_response: true
