name: Deploy OmniBridge Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar arquivos .env
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" > .env

          echo "PORT=3001" > gateway-api/.env
          echo "LITELLM_BASE_URL=http://litellm:4007/v1" >> gateway-api/.env
          echo "LITELLM_API_KEY=${{ secrets.LITELLM_API_KEY }}" >> gateway-api/.env

      - name: Build e deploy
        run: |
          docker compose build --no-cache gateway-api
          docker compose up -d

      - name: Limpeza de imagens antigas
        run: docker image prune -f
